// Copyright 2026 Simon Liimatainen. All rights reserved.
#include "core/draw/planets/PlanetDrawer.h"
#include "core/draw/planets/TerrainPatch.h"
#include "core/gpu/Device.h"
#include "core/gpu/Material.h"
#include "core/include/shared/Transform.h"
#include "core/types/glm_conversions.h"
#include "core/types/Math.h"

#include "core/engine/Camera.h"
#include "core/world/World.h"
#include "core/world/Scene.h"
#include "core/world/Sector.h"

#include <stdexcept>
#include <array>
#include <limits>
#include <utility>
#include <numbers>
#include <chrono>

// glm
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/constants.hpp>

#include <cmath>
#include <chrono>
#include <iostream>
#include "core/engine/EngineClock.h"

namespace EngineCore
{
	using namespace WorldSystem;

	struct FaceBasis
	{
		Vec right;
		Vec up;
		Vec forward;
	};

	FaceBasis getFaceBasis(ETerrainPatchFaceDirection face)
	{
		switch (face)
		{
		case ETerrainPatchFaceDirection::A: return { {0,0,1}, {0,1,0}, {1,0,0} };
		case ETerrainPatchFaceDirection::B: return { {0,0,-1}, {0,1,0}, {-1,0,0} };
		case ETerrainPatchFaceDirection::C: return { {1,0,0}, {0,0,1}, {0,1,0} };
		case ETerrainPatchFaceDirection::D: return { {1,0,0}, {0,0,-1}, {0,-1,0} };
		case ETerrainPatchFaceDirection::E: return { {1,0,0}, {0,1,0}, {0,0,1} };
		case ETerrainPatchFaceDirection::F: return { {-1,0,0}, {0,1,0}, {0,0,-1} };
		}
		return { {1,0,0}, {0,1,0}, {0,0,1} };
	}

	constexpr uint32_t maxLOD = 16;			// maximum depth of the quadtree
	constexpr double lodFactor = 2.4;		// distance split threshold multiplier
	constexpr bool shaderDesignMode = true; // periodically reload shaders, slow but useful for quick changes

	PlanetDrawer::PlanetDrawer(EngineDevice& device, World& world, const RenderingFormats& formats, VkSampleCountFlagBits samples)
		: device(device), world(world), junkPileMutexes({{},{}})
	{
		// create a planet made up of one node per root face
		planets.push_back(std::make_unique<Planet>());
		Planet& planet = *planets.back();
		planet.resolution = 64;
		planet.radius = 6371 * 100000; // radius of earth
		planet.transform.sector = { 0, 0, 0 };

		// create material
		ShaderFilePaths shaders(makePath("shaders/compiled/planet.vert.spv"), makePath("shaders/compiled/planet.frag.spv"));
		auto layouts = world.getScene().getDescriptorSetLayouts();
		MaterialCreateInfo matInfo(shaders, layouts, samples, formats, sizeof(ShaderPushConstants::PlanetMeshPushConstants), EMatSet::NO);
		matInfo.shadingProperties.polygonMode = VK_POLYGON_MODE_FILL;
		matInfo.shadingProperties.cullModeFlags = VK_CULL_MODE_NONE;
		planet.material = std::make_shared<Material>(matInfo, device);
		planet.material->finalize();

		for (auto& pile : junkPiles) pile.reserve(1000);
		
		updater = std::thread(&PlanetDrawer::asyncUpdate, this);
	}

	PlanetDrawer::~PlanetDrawer()
	{
		updaterExit = true;
		updater.join();
	}

	std::vector<std::unique_ptr<JunkPileItem>>& PlanetDrawer::getJunkPile(uint32_t threadIndex)
	{
		return junkPiles[(currentFrameIndex + threadIndex) % junkPiles.size()];
	}

	void PlanetDrawer::ensureJunkPileLock(uint32_t threadIndex, std::unique_lock<std::mutex>& lock)
	{
		auto& m = junkPileMutexes[(currentFrameIndex + threadIndex) % junkPiles.size()];
		lock = std::move(std::unique_lock<std::mutex>(m, std::try_to_lock));
		assert(lock.owns_lock() && "unsafe to free from and write to the same junk pile concurrently");
	}

	// patches are regenerated by the updater thread, which are stored as replacement objects under the existing patches, in TerrainPatch::next
	// geometry is uploaded to GPU by the updater thread, which waits for commands to finish before unlocking
	// the render thread replaces patches with their new "next" when they become available, updaterDoneMutex protects concurrent access to TerrainPatch::next

	void PlanetDrawer::render(VkCommandBuffer commandBuffer, uint32_t frameIndex, const Transform& cameraTransform, double dt)
	{
		currentFrameIndex = frameIndex;
		delta = dt;
		cmdBuffer = commandBuffer;
		camTransform = cameraTransform;
		Scene& scene = world.getScene();
		const auto sets = scene.getDescriptorSets(frameIndex);

		if (updaterIdle)
		{
			if (reloadShadersNextFrame)
			{
				// shader design mode only
				device.waitGraphicsQueueIdle(); // wait until all draw commands are done
				updaterIdle = false; // instruct the updater thread to reload shaders
				while (reloadShadersNextFrame); // wait until reload is done
				return;
			}
			else
			{
				// instruct the updater thread to do a LOD pass
				updaterIdle = false;
			}
		}

		Material* currentMaterial = nullptr;
		for (const auto& planet : planets)
		{
			if (planet->material.get() != currentMaterial)
			{
				// bind planet's material
				currentMaterial = planet->material.get();
				currentMaterial->bindToCommandBuffer(commandBuffer);
				vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, currentMaterial->getPipelineLayout(),
						0, static_cast<uint32_t>(sets.size()), sets.data(), 0, nullptr);
			}

			// draw patches
			for (std::unique_ptr<TerrainPatch>& rootPatch : planet->roots)
			{
				attemptReplace(rootPatch);
				drawRecursive(rootPatch, *planet);
			}
		}
	}

	void PlanetDrawer::createRootFaces()
	{
		// create each root face (the 6 sides of a cube-sphere)
		assert(planets[0]->roots.size() == 0);
		for (auto& planet : planets)
		{
			for (uint32_t i = 0; i < 6; i++)
			{
				planet->roots.push_back(std::make_unique<TerrainPatch>(device, planet->resolution, planet->radius));
				TerrainPatch& root = *planet->roots.back();

				// set up quad metadata for root
				root.center = { -1.0f, -1.0f }; // using bottom-left as offset
				root.size = 2.0f; // full extent of the face
				root.lodLevel = 0;
				root.face = static_cast<ETerrainPatchFaceDirection>(i);
				root.generate(*asyncCmdBuffer);
			}
		}
	}

	void PlanetDrawer::asyncUpdate()
	{
		while (not updaterExit)
		{
			if (not firstGeometryReady)
			{
				asyncCmdBuffer = device.getAsyncCommandDispatcher().makeNewCommandBuffer();
				asyncCmdBuffer->start();
				createRootFaces(); // initialize cube-sphere when started for the first time
			}

			while (updaterIdle && not updaterExit) std::this_thread::sleep_for(std::chrono::milliseconds(1));
			if (updaterExit) break;
			if (shaderDesignMode) tickShaderDesignMode(); // periodically reload shaders (design mode only)

			cleanJunkPile(currentFrameIndex);

			if (firstGeometryReady) asyncCmdBuffer->start();

			// the lock is held until all TerrainPatch::next patches are constructed, and until GPU uploads finish
			std::unique_lock<std::mutex> lock(updaterDoneMutex);

			for (const auto& planet : planets)
			{
				for (std::unique_ptr<TerrainPatch>& patch : planet->roots)
				{
					// update patch and its children
					evaluatePatchLOD(*patch, *planet);
				}
			}

			asyncCmdBuffer->submit();
			asyncCmdBuffer->wait(30000);
			firstGeometryReady = true;
			updaterIdle = true;
		}
		asyncCmdBuffer.reset();
	}

	void PlanetDrawer::evaluatePatchLOD(TerrainPatch& patch, Planet& planet)
	{
		if (patch.next) return;
		uint32_t action = checkSplitCriteria(patch, planet);
		if (action == 1)
		{
			// the patch is a leaf, split it
			patch.splitReplace(*asyncCmdBuffer);
		}
		else if (action == 2)
		{
			// distance is too far, remove geometry from child patches 
			patch.mergeReplace(*asyncCmdBuffer);
		}
		else
		{
			// recursively update children (skip if patch was just split)
			for (auto& child : patch.children)
			{
				evaluatePatchLOD(*child, planet);
			}
		}

	}

	uint32_t PlanetDrawer::checkSplitCriteria(TerrainPatch& patch, Planet& planet)
	{
		// get 2D center of this patch
		const float halfSize = patch.size * 0.5f;
		const Vec2 localCenter2D =
		{
			patch.center.x + halfSize,
			patch.center.y + halfSize
		};

		// project 2D center to 3D unit sphere direction
		const FaceBasis basis = getFaceBasis(patch.face);

		// apply equiangular warping to match mesh geometry
		constexpr double PI_OVER_4 = 0.78539816339;
		float tan_x = static_cast<float>(std::tan(localCenter2D.x * PI_OVER_4));
		float tan_y = static_cast<float>(std::tan(localCenter2D.y * PI_OVER_4));
		const Vec cubePoint = basis.forward + (basis.right * tan_x) + (basis.up * tan_y);

		const Vec unitDirection = cubePoint.getNormalized();

		// true world-space position of patch center (planet is assumed to be at the center of its own sector)
		const Vec patchCenter = unitDirection * static_cast<float>(planet.radius);

		// true distance to camera
		const Transform patchTransform(patchCenter, Vec(0), Vec(0), planet.transform.sector);

		const double distanceToCamera = Math::calculateDistance(patchTransform, camTransform);

		// estimate physical size of patch on the sphere surface (a root patch of size 2 spans roughly 90 deg / PI half-circumference)
		const double patchArcLength = (static_cast<double>(patch.size) / 2.0) * (std::numbers::pi * 0.5) * planet.radius;

		const double targetDistance = patchArcLength * lodFactor;

		// check split criteria - use a higher distance multiplier to merge than to split
		const bool split = (distanceToCamera < targetDistance) && (patch.lodLevel < maxLOD) && patch.stateIs(TerrainPatch::EState::LEAF);
		const bool merge = (distanceToCamera > targetDistance * 1.15) && patch.children.size();
		return (split || merge) ? (split ? 1 : 2) : 0;
	}


	void PlanetDrawer::drawRecursive(std::unique_ptr<TerrainPatch>& patch, Planet& planet)
	{
		if (not firstGeometryReady) return;
		if (patch->isParent())
		{
			for (auto& childPatch : patch->children)
			{
				attemptReplace(childPatch);
				drawRecursive(childPatch, planet);
			}
		}
		else
		{
			drawLeafPatch(patch, planet);
		}
	}

	void PlanetDrawer::attemptReplace(std::unique_ptr<TerrainPatch>& patch)
	{
		// only replace patches when the updater thread is idle, but do not wait for it, as that would lower FPS when terrain is being generated
		std::unique_lock<std::mutex> lock(updaterDoneMutex, std::try_to_lock);
		if (lock.owns_lock() && patch->next)
		{
			// this patch has an updated version ready, replace it
			std::unique_ptr<TerrainPatch> next = std::move(patch->next);

			std::unique_lock<std::mutex> trashLock;
			ensureJunkPileLock(0, trashLock);
			patch->scheduleFreeBuffersRecursive(getJunkPile(0), currentFrameIndex);
			patch->children.clear();

			patch = std::move(next);
		}
	}

	void PlanetDrawer::drawLeafPatch(std::unique_ptr<TerrainPatch>& patch, Planet& planet)
	{
		if (not patch->stateIs(TerrainPatch::EState::LEAF)) return;

		// translation and scaling factor
		Vec position;
		double k = 1;

		const Vec64 rel = Math::calculateRelativeCoordsXYZ(camTransform, planet.transform);
		const double distance = rel.getLength();
		if (distance > finalDrawDistance) [[likely]]
		{
			// generate new position relative to player's sector, pinned to a certain distance so it stays closer than the far clip plane
			Vec direction =
			{
				static_cast<float>(rel.x / distance),
				static_cast<float>(rel.y / distance),
				static_cast<float>(rel.z / distance)
			};
			position = camTransform.translation + direction * finalDrawDistance;

			k = finalDrawDistance / distance;
		}
		else [[unlikely]]
		{
			// this usually won't happen unless the radius is tiny, or we go underground
			position = Math::calculateRelativePositionForRendering(planet.transform, camTransform.sector);
		}

		// the unit sphere is scaled up to its final radius in the shader
		const double visualRadius = planet.radius * k;
		const Vec scale = Vec(static_cast<float>(visualRadius));

		ShaderPushConstants::PlanetMeshPushConstants push{};
		// TODO: optimize this
		push.transform = EngineCore::cglm::makeMatrixQ(Vec(0), 1.f, scale, position);
		push.normalMatrix = glm::transpose(glm::inverse(push.transform));
		push.cameraPositionAndLOD.x = camTransform.translation.x;
		push.cameraPositionAndLOD.y = camTransform.translation.y;
		push.cameraPositionAndLOD.z = camTransform.translation.z;
		push.cameraPositionAndLOD.w = static_cast<float>(patch->lodLevel);

		planet.material->writePushConstants(cmdBuffer, push);
		// record mesh draw command
		patch->draw(cmdBuffer);
	}

	int32_t PlanetDrawer::acquireJunkPile(std::unique_lock<std::mutex>& lock, bool allowFail)
	{
		// try to acquire any available mutex without waiting
		//for (uint32_t i = 0; i < junkPileMutexes.size(); i++)
		//{
		//	std::unique_lock<std::mutex> tryLock(junkPileMutexes[i], std::try_to_lock);
		//	if (tryLock.owns_lock())
		//	{
		//		lock = std::move(tryLock);
		//		return i;
		//	}
		//}
		//if (allowFail) return -1;
		//
		//// if none were free, do a blocking wait
		//lock = std::unique_lock<std::mutex>(junkPileMutexes[0]);
		return 0;
	}

	// do not call this on the exact same frame as marking items to be freed
	void PlanetDrawer::cleanJunkPile(uint32_t cleaningFrameIndex)
	{
		std::unique_lock<std::mutex> trashLock;
		ensureJunkPileLock(1, trashLock);

		auto& junkPile = getJunkPile(1);
		std::erase_if(junkPile, [cleaningFrameIndex](const auto& item)
			{
				return item->freeOnFrameIndex == cleaningFrameIndex;
			});
		//if (junkPile.size()>0) std::cout << (currentFrameIndex + 1) % junkPiles.size() << " junk pile size: " << junkPile.size() << "\n";
	}

	void PlanetDrawer::tickShaderDesignMode()
	{
		if (reloadShadersNextFrame)
		{
			for (const auto& planet : planets)
			{
				MaterialCreateInfo matInfo = planet->material->getMaterialCreateInfo();
				planet->material = std::make_shared<Material>(matInfo, device);
				planet->material->finalize();
			}
			reloadShadersNextFrame = false; // signal to render thread that the shader reload completed
		}
		else
		{
			shaderReloadTimer -= delta;
			if (shaderReloadTimer <= 0)
			{
				shaderReloadTimer = 1.2;
				reloadShadersNextFrame = true;
			}
		}
	}
}